- recipe/meta.yaml
> version 0.4.0 build 0 dependency cython planarity

- recipe/meta.yaml
> two-line script

- recipe/meta.yaml
> Add the new python-planarity dependency including windows

- recipe/meta.yaml
> release v0.4.6

- recipe/meta.yaml
> Release 0.4.7

- recipe/meta.yaml
> Release 0.4.8

- recipe/meta.yaml
> update to new version

- recipe/meta.yaml
> update to v0.4.19

- recipe/meta.yaml
> update to v0.4.20

- recipe/meta.yaml
> update to v0.4.23

- .azure-pipelines/azure-pipelines-linux.yml
- .ci_support/linux_python2.7.yaml
- .circleci/config.yml
- recipe/meta.yaml
> Bump build to specify min dependencies

- recipe/meta.yaml
> update to 0.6.1

- recipe/meta.yaml
> update to 0.7.1

- recipe/meta.yaml
> Match matplotlib requirement to requirements.txt

- recipe/meta.yaml
> Declare entry point scripts

- recipe/meta.yaml
> Add imageio to match requirements.txt dependencies

- recipe/meta.yaml
> Match requirements.txt and remove py27 stuff

- recipe/meta.yaml
> updated requirements and bumped version

- recipe/meta.yaml
> removing polyfempy

- recipe/meta.yaml
> removing wildmeshing

- recipe/meta.yaml
> update to 0.16.9

- recipe/meta.yaml
> bump to 0.17.1

- recipe/meta.yaml
> update to 0.17.2

- recipe/meta.yaml
> Specific numpy deps

- recipe/meta.yaml
New recipes generated with conda's new-ish [grayskull](https://pypi.org/project/grayskull/) add this `pip check` test to ensure the requirements in sync between pip and conda.
Checklist
> Release 1.4.0 and add pip check to ensure pip and conda requirements are in sync

- recipe/meta.yaml
> Release 1.7.1

- .azure-pipelines/azure-pipelines-win.yml
- .circleci/config.yml
- recipe/meta.yaml
> Release 1.16.0 + match requirements

- README.md
- recipe/meta.yaml
> remove cython and pycollada

- recipe/meta.yaml
> numpy restriction

- recipe/meta.yaml
> Numpy upper bound
